### ISSUE TITLE
Error when using !tm

### ISSUE THREAD

**Issue by Newtim** [shdwjk/Roll20API#16]
This is the error I get when utilizing !tm command.  I will start a new campaign and see if another macro is causing.
TypeError: Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at getFrom (apiscript.js:13223:43)
    at apiscript.js:13212:31
    at eval (eval at <anonymous> (/home/node/d20-api-server/api.js:146:1), <anonymous>:65:16)
    at Object.publish (eval at <anonymous> (/home/node/d20-api-server/api.js:146:1), <anonymous>:70:8)
    at /home/node/d20-api-server/api.js:1510:12
    at /home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:560
    at hc (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:39:147)
    at Kd (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:546)
    at Id.Mb (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:489)
    at Zd.Ld.Mb (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:94:425)
    at /home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:111:400

**Comment by Newtim** [comment]
found culprit was macro named Rollable Table Macros, not sure what the problem is or how to fix.

**Comment by shdwjk** [comment]
Do you mean you have a script named `Rollable Table Macros` that was causing the issue?  There isn't a `getFrom()` function in any of my scripts that I can find, nor in the Roll20 official repo's scripts.  If you want to PM me on Roll20, I can probably help you track the issue down in game.

**Comment by Newtim** [comment]
Yes it was a script named Rollable table macros, I switched to recursive table.

**Comment by Newtim** [comment]
This is fixed by removing Rollable Table Macros
