### ISSUE TITLE
MapLock lock fails

### ISSUE THREAD

**Issue by scarolan** [shdwjk/Roll20API#23]
Attempting to use the MapLock API script, when I try to select the map image and run `!map-lock lock` this is what shows up in the console:

For reference, the error message generated was: ReferenceError: $d is not defined
ReferenceError: $d is not defined
    at apiscript.js:101:17
    at Function._.each._.forEach (/home/node/d20-api-server/node_modules/underscore/underscore.js:186:9)
    at _.(anonymous function) [as each] (/home/node/d20-api-server/node_modules/underscore/underscore.js:1639:39)
    at tintGraphics (apiscript.js:99:14)
    at handleInput (apiscript.js:151:29)
    at eval (eval at <anonymous> (/home/node/d20-api-server/api.js:151:1), <anonymous>:65:16)
    at Object.publish (eval at <anonymous> (/home/node/d20-api-server/api.js:151:1), <anonymous>:70:8)
    at /home/node/d20-api-server/api.js:1634:12
    at /home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:560
    at hc (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:39:147)

**Comment by scarolan** [comment]
I was using an older version, closing this.
